FROM maven:3.9.4-eclipse-temurin-21-alpine AS build

COPY..

RUN mvn clean package -DskipTests

FROM openjdk:21-slim

COPY --from=build target/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java","-jar","/app.jar"]