# Use OpenJDK 21 as base image
FROM openjdk:21

# Set working directory
WORKDIR /app

# Copy Maven project files
COPY target/JwtExample3-0.0.1-SNAPSHOT.jar /app/JwtExample3-0.0.1-SNAPSHOT.jar

# Expose the default Spring Boot port
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "JwtExample3-0.0.1-SNAPSHOT.jar"]
